name: "imgcmp"
description: "Optimize images in your repository. Supported image file formats: JPEG, PNG, GIF, SVG, WEBP"
author: "9sako6"
branding:
  icon: "image"
  color: "blue"
inputs:
  token:
    description: "A Personal Access Token. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token"
    required: true
  paths-ignore-regexp:
    description: "A regular expression for images' paths you don't want to compress."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      with:
        node-version: "16"
    - name: Install cwebp, gifsicle, jpegoptim, optipng, svgo
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        echo "::group::Install cwebp, gifsicle, jpegoptim, optipng, svgo"
        sudo apt-get install -y webp gifsicle jpegoptim optipng
        npm install -g svgo
        echo "::endgroup::"
        echo "::group::cwebp"
        cwebp -version
        echo "::endgroup::"
        echo "::group::gifsicle"
        gifsicle --version
        echo "::endgroup::"
        echo "::group::jpegoptim"
        jpegoptim --version
        echo "::endgroup::"
        echo "::group::optipng"
        optipng -v
        echo "::endgroup::"
        echo "::group::svgo"
        svgo -v
        echo "::endgroup::"
    - uses: actions/checkout@v2
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
    - name: Optimize images
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        echo "::group::cwebp"
        find * -type f | grep .webp | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} cwebp {} -o {} && true
        echo "::endgroup::"
        echo "::group::gifsicle"
        find * -type f | grep .gif | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} gifsicle -b -O3 --colors 256 {} && true
        echo "::endgroup::"
        echo "::group::optipng"
        find * -type f | grep .png | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} optipng -o2 {} && true
        echo "::endgroup::"
        echo "::group::jpegoptim"
        find * -type f | grep .jpg | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} jpegoptim -m85 {} && true
        find * -type f | grep .jpeg | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} jpegoptim -m85 {} && true
        echo "::endgroup::"
        echo "::group::svgo"
        find * -type f | grep .svg | grep -vE '${{ inputs.paths-ignore-regexp }}' | xargs -I{} svgo {} && true
        echo "::endgroup::"
    - name: Check if images were compressed
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        if [ -z "$(git diff --name-only)" ]; then
          echo 'There was no change in all the images.'
          echo "::set-output name=no_change::true"
        else
          echo "::group::git diff"
          git diff --name-only
          echo "::endgroup::"
        fi
      id: diff
    - name: Commit images
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        if [ -n "${{ steps.diff.outputs.no_change }}" ]; then
          echo 'This step is skipped.'
          exit 0
        fi
        git config --local user.name "GitHub"
        git config --local user.email "noreply@github.com"
        git tag v0
        git add .
        git commit -m "Optimize images"
        sha=$(git rev-parse --short HEAD)
        new_branch="actions/imgcmp/${sha}"
        # git switch -c ${new_branch}
        # git tag v1
        echo ::set-output name=sha::${sha}
        echo ::set-output name=new_branch::${new_branch}
      id: commit
    - name: Sample
      shell: bash
      run: |
        node -e "$(curl https://raw.githubusercontent.com/9sako6/imgcmp/use-create-pull-request-action/index.js)"
    # - name: Commit images
    #   if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
    #   shell: bash
    #   run: |
    #     git config --local user.name "GitHub"
    #     git config --local user.email "noreply@github.com"
    #     git add .
    #     git commit -m "Optimize images"
    #   id: commit
    # - name: Edit the commit message.
    #   if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
    #   shell: bash
    #   run: |
    #     if [ -n "${{ steps.diff.outputs.no_change }}" ]; then
    #       echo 'This step is skipped.'
    #       exit 0
    #     fi
    #     git switch ${{ steps.commit.outputs.new_branch }}
    #     git commit --amend -m '${{ steps.template.outputs.title }}'
    - name: Create a pull request
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ inputs.token }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: ${{ steps.commit.outputs.new_branch }}
        title: 'Auto PR'
        body: 'This is a sample pull request.'
        draft: false
