name: "imgcmp"
description: "A GitHub Action that automatically optimizes images in your repository. Supported image file formats: JPEG, PNG, GIF, SVG, WEBP"
author: "9sako6"
runs:
  using: "docker"
  image: "Dockerfile"
