name: "imgcmp"
description: "Optimize images in your repository. Supported image file formats: JPEG, PNG, GIF, SVG, WEBP"
author: "9sako6"
branding:
  icon: "image"
  color: "blue"
inputs:
  token:
    description: "A Personal Access Token. See https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token"
    required: true
  paths-ignore-regexp:
    description: "A regular expression for images' paths you don't want to compress."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      with:
        node-version: "16"
    - name: Install deno
      shell: bash
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      run: |
        curl -fsSL https://deno.land/install.sh | sh
    - name: Install cwebp, gifsicle, jpegoptim, optipng, svgo
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        echo "::group::Install cwebp, gifsicle, jpegoptim, optipng, svgo"
        sudo apt-get install -y webp gifsicle jpegoptim optipng
        npm install -g svgo
        cwebp -version
        gifsicle --version
        jpegoptim --version
        optipng -v
        svgo -v
    - uses: actions/checkout@v2
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
    - name: Export images' statistics in json before optimization
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        /home/runner/.deno/bin/deno run \
          --allow-read \
          --allow-write \
          https://raw.githubusercontent.com/9sako6/imgcmp/use-create-pull-request-action/src/export_stat.ts \
          '${{ inputs.paths-ignore-regexp }}' \
          '/tmp/imgcmp-stat.json'
        cat '/tmp/imgcmp-stat.json'
    - name: Optimize images
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        /home/runner/.deno/bin/deno run \
          --allow-read \
          --allow-run \
          https://raw.githubusercontent.com/9sako6/imgcmp/use-create-pull-request-action/src/optimize.ts \
          '${{ inputs.paths-ignore-regexp }}'
    - name: Export images' statistics in json after optimization
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        /home/runner/.deno/bin/deno run \
          --allow-read \
          --allow-write \
          https://raw.githubusercontent.com/9sako6/imgcmp/use-create-pull-request-action/src/export_stat.ts \
          '${{ inputs.paths-ignore-regexp }}' \
          '/tmp/imgcmp-stat.json'
        cat '/tmp/imgcmp-stat.json'
    - name: Export images' statistics in json after optimization
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        message=$(/home/runner/.deno/bin/deno run \
          --allow-read \
          https://raw.githubusercontent.com/9sako6/imgcmp/use-create-pull-request-action/src/show_stat_message.ts \
          '/tmp/imgcmp-stat.json'
        )
        title=$(cat << EOS | head -n 1
        ${message}
        EOS
        )
        echo $message
        echo $title
        echo ::set-output name=message::${message}
        echo ::set-output name=title::${title}
      id: template
    - name: Check if images were compressed
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        if [ -z "$(git diff --name-only)" ]; then
          echo 'There was no change in all the images.'
          echo "::set-output name=no_change::true"
        else
          echo "::group::git diff"
          git diff --name-only
          echo "::endgroup::"
        fi
      id: diff
    - name: Commit images
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      shell: bash
      run: |
        if [ -n "${{ steps.diff.outputs.no_change }}" ]; then
          echo 'This step is skipped.'
          exit 0
        fi
        git config --local user.name "GitHub"
        git config --local user.email "noreply@github.com"
        git tag v0
        git add .
        git commit -m "Optimize images by imgcmp action"
        sha=$(git rev-parse --short HEAD)
        new_branch="actions/imgcmp/${sha}"
        # git switch -c ${new_branch}
        # git tag v1
        echo ::set-output name=sha::${sha}
        echo ::set-output name=new_branch::${new_branch}
      id: commit
    - name: Create a pull request
      if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
      uses: peter-evans/create-pull-request@v3.14.0
      with:
        token: ${{ inputs.token }}
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: ${{ steps.commit.outputs.new_branch }}
        title: "Optimize images by imgcmp action"
        body: ${{ steps.template.outputs.message }}
        draft: false
