name: imgcmp
on: push
jobs:
  main-flow:
    name: imgcmp
    runs-on: ubuntu-latest    
    steps:
    - uses: 9sako6/imgcmp@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IGNORED_FILES: "figs/logo.png"
  cache-go:
    needs: main-flow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('/usr/local/go/src/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-