name: imgcmp-push-pat
on:
  - push
  - workflow_dispatch
jobs:
  imgcmp-push-pat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ./
        id: imgcmp
        with:
          token: ${{ secrets.IMGCMP_ACCESS_TOKEN }}
          paths-ignore-regexp: 'figs/logo\.png'
      - name: Close Pull
        if: steps.imgcmp.outputs.pull-request-number != ''
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: ${{ steps.imgcmp.outputs.pull-request-number }}
          comment: Auto-closing pull request
          delete-branch: true
