name: imgcmp
on: [push, pull_request]
jobs:
  imgcmp:
    if: startsWith(github.head_ref, 'actions/imgcmp/') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          paths-ignore-regexp: 'figs/logo\.png'
      - name: Close Pull
        uses: peter-evans/close-pull@v2
        with:
          comment: Auto-closing pull request
          delete-branch: true
