name: imgcmp-test
on: push
jobs:
  main-flow:
    runs-on: ubuntu-latest    
    steps:
    - uses: 9sako6/imgcmp@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IGNORED_FILES: "figs/logo.png"
        DEBUG_IMGCMP: true