name: CI
on: push
jobs:
  test:
    if: ${{ startsWith(github.head_ref, 'actions/imgcmp/') != true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.IMGCMP_ACCESS_TOKEN }}
          paths-ignore-regexp: 'figs/logo\.png'
